version: "3.3"
services:
  frontend:
    build: sus-frontend/.
    ports:
      - "3000:3000"
  backend:
    build: sus-backend/.
    ports:
      - "8080:8080"
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  volumes:
    data: {}
